version: '3'
services:
  # consul
  consul-server1:
    image: consul:latest
    hostname: "consul-server1"
    ports:
      - "8501:8500"
      - "53"
    volumes:
      - ./config/consul/data1:/consul/data
    command: "agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0"
  consul-server2:
    image: consul:latest
    hostname: "consul-server2"
    ports:
      - "8502:8500"
      - "53"
    volumes:
      - ./config/consul/data2:/consul/data
    command: "agent -server -ui -join consul-server1 -disable-host-node-id -client 0.0.0.0"
    depends_on:
      - consul-server1
  consul-server3:
    image: consul:latest
    hostname: "consul-server3"
    ports:
      - "8503:8500"
      - "53"
    volumes:
      - ./config/consul/data3:/consul/data
    command: "agent -server -ui -join consul-server1 -disable-host-node-id -client 0.0.0.0"
    depends_on:
      - consul-server1
  consul-node1:
    image: consul:latest
    hostname: "consul-node1"
    command: "agent -join consul-server1 -disable-host-node-id"
    depends_on:
      - consul-server1
  consul-node2:
    image: consul:latest
    hostname: "consul-node2"
    command: "agent -join consul-server1 -disable-host-node-id"
    depends_on:
      - consul-server1
      
  # nginx
  nginx:
    image: nginx
    ports:
      - 8081:80/tcp
      - 8500:8500/tcp
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/www:/usr/share/nginx/html
      - ./config/nginx/logs:/var/log/nginx
      
  # ocelot
  ocelot:
    build:
      context: GateWays/
    image: ocelot
    ports:
      - 9001:80/tcp
  ocelot1:
    image: ocelot
    ports:
      - 9002:80/tcp